image: node

stages:
  - test
  - build
  - deploy

before_script:
  - "npm install"

test:
  stage: test
  script:
    - "echo 'Running tests for Feedback-App'"
    - "npm run test"

build:
  stage: build
  script:
    - "echo 'Building Feedback-App'"
    - "npm run build"

deploy:
  stage: deploy
  environment:
    name: production
    url: https://feedback.mayflower.de
  script:
    - "echo 'Building Feedback-App for production deployment'"
    - "npm run build"
    - "echo 'Deploying Feedback-App to production'"
    - "apt-get update"
    - "apt-get install --yes rsync"
    - "touch cfq_deploy"
    - "chmod go-rwx cfq_deploy"
    - "echo $DEPLOY_ED25519 > cfq_deploy"
    - "sed -i -e 's/\\r /\\n/g' cfq_deploy"
    - "mkdir -p ~/.ssh/"
    - "echo $DEPLOY_HOST_KEY > ~/.ssh/known_hosts"
    - "chmod go-rwx -R ~/.ssh/"
    - "rsync -v -r --delete -e 'ssh -4 -i cfq_deploy' build/ cfq-deploy@webnix.mgmt.fs.mayflower.zone:/srv/www/cfq.mayflower.de/htdocs/"
  only:
    - master
